export { default as HomePage } from './home-page'
export { default as LoginPage } from './login-page'
export { default as AdPage } from './ads-page'
export { default as AdSinglePage } from './ads-single-page'
export { default as MusicianPage } from './musicians-page'
export { default as MusicianSinglePage } from './musicians-single-page'
export { default as BandPage } from './bands-page'
export { default as BandSinglePage } from './bands-single-page'
